import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { auth } from "../../../auth";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { GithubIcon } from "lucide-react";
import { login } from "./lib/actions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //Next-Auth's session to be passed as props to my Navbar
  const session = await auth();
  return (
    <html lang="en bg-secondary">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <main className="flex justify-center items-center h-screen">
          <div className="flex flex-col gap-5 w-[90%] sm:w-96 shadow p-4">
            {children}
            <Separator />
            <form>
              <Button type="submit" formAction={login} className="w-full">
                <GithubIcon />
                Continue with Github
              </Button>
            </form>
          </div>
        </main>
      </body>
    </html>
  );
}
